services:
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
  # fake log generator
  flog:
    image: mingrammer/flog
    command: ["-s","10s","-n","25"] 
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  #jaeger:
    #image: jaegertracing/all-in-one:1.59
    #environment:
      #- COLLECTOR_ZIPKIN_HOST_PORT=:9411
    #ports:
      #- 4317:4317
      #- 4318:4318
      #- 5778:5778
      #- 6831:6831/udp
      #- 6832:6832/udp
      #- 9411:9411
      #- 14250:14250
      #- 14268:14268
      #- 14269:14269
      #- 16686:16686
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    #volumes:
      #- ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #command:
      #- --config.file=/etc/prometheus/prometheus.yaml
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"    # tempo
      - "4317:4317"    # otlp grpc
      - "4318:4318"    # otlp http
      - "9095:9095"    # tempo grpc
      - "9411:9411"    # zipkin
      - "14268:14268"  # jaeger ingest
